Add support for DECRQM/DECRPM
alacritty/vte pull request #104
Opened 2023-11-14 21:47 UTC by kchibisov

Fixes #100.

2023-11-14 22:14 UTC, chrisduerr requested changes

2023-11-14 22:14 UTC, chrisduerr commented on CHANGELOG.md
> +- Add `Handler::report\_mode` handling DECRQM/DECRPM
This is not what the function is called.

2023-11-14 22:14 UTC, chrisduerr commented on src/ansi.rs
> +    fn pty_write(&mut self, _payload: String) {}
VTE writing arbitrary stuff shouldn't be a thing. There's a reason why this is a trait-based interface, we should have proper functions here.

2023-11-14 22:14 UTC, chrisduerr commented on src/ansi.rs
> +    fn report_mode(&mut self, _reporter: ModeReporter, _mode: Mode) {}
Why is this passing two separate modes?

2023-11-17 01:48 UTC, kchibisov commented
I guess this is fine? Or do we want a similar `Reporter` thing I had to help building downstream an escape sequence?

2023-11-17 02:31 UTC, chrisduerr approved these changes

2023-11-17 03:12 UTC, kchibisov commented
Added `Clone + Copy` on private mode, because it was on public, but not on private one.

2023-11-17 03:20 UTC, merged