Bump rust-version to match actual MSRV
alacritty/vte pull request #89
Opened 2023-05-24 12:21 UTC by djc

#85 bumped the MSRV but failed to bump the `rust-version` in `Cargo.toml`.

2023-05-24 12:25 UTC, djc commented
CI failures are unrelated, just clippy lints.

2023-05-24 12:30 UTC, kchibisov commented
Is clippy considering `rust-version` when running? As you can see, the CI with the same rust version is passing on current master, so it's related to your patch.

2023-05-24 21:31 UTC, chrisduerr requested changes
Can you change CI to use this script instead of relying on a manually set MSRV:

https://github.com/catacombing/catacomb/blob/master/.github/workflows/ci.yml#L21-L26

2023-05-25 22:05 UTC, chrisduerr approved these changes
Thanks

2023-05-25 22:08 UTC, chrisduerr requested changes

2023-05-25 22:08 UTC, chrisduerr commented on .builds/linux.yml
>        cd vte
This `cd` statement needs to be moved to the top.

2023-05-26 09:24 UTC, djc commented
Fixed. As a point of feedback, as a drive-by contributor fixing up an oversight from an earlier PR, it doesn't feel great that you've blocked this PR on fixing up the CI flow (which then resulted in another round trip to deal with the error).

2023-05-26 09:39 UTC, kchibisov commented
>Fixed. As a point of feedback, as a drive-by contributor fixing up an oversight from an earlier PR, it doesn't feel great that you've blocked this PR on fixing up the CI flow (which then resulted in another round trip to deal with the error).

There's no need to merge subpar code if we could have something more manageable. If you as a contributor doesn't want to do extra work that was explicitly requested, you're free to close your PR and we as a maintainers could pick it up. It's your choice in the end of the day whether you want to continue with the review or not. We don't ought each other anything in the end of the day.

2023-05-26 09:48 UTC, djc commented
I just disagree that it's subpar -- it's strictly better than what it was before. You're asking me to implement an extra improvement that makes your life as maintainers easier. Anyway, I'm just giving feedback, up to you what you do with it.

2023-05-26 09:56 UTC, kchibisov commented
>You're asking me to implement an extra improvement that makes your life as maintainers easier

I'm just saying that you could disagree with this at any point of time, so we implement it instead.

2023-05-26 23:05 UTC, chrisduerr commented
> Fixed. As a point of feedback, as a drive-by contributor fixing up an oversight from an earlier PR, it doesn't feel great that you've blocked this PR on fixing up the CI flow (which then resulted in another round trip to deal with the error).

Considering I've linked you the exact bash line to fix it and that was absolutely trivial, I'm honestly shocked at how much time it took you.

If you can't figure out something so trivial, I'd recommend not pointlessly wasting maintainers' time on spoonfeeding you solutions and just skipping the PR submission entirely.

2023-05-26 23:06 UTC, chrisduerr approved these changes

2023-05-26 23:06 UTC, merged